spark.eventLog.enabled=true
spark.eventLog.dir=/opt/spark-logs
spark.history.fs.logDirectory=/opt/spark-logs
spark.ui.reverseProxy=false
spark.history.fs.cleaner.enabled=true
spark.history.fs.cleaner.maxAge=3h
spark.history.fs.cleaner.interval=1h
spark.worker.cleanup.enabled=true
spark.worker.cleanup.interval=300
spark.worker.cleanup.appDataTtl=1800
