[build-system]
requires = [
  "setuptools>=61.0",
  "python-dateutil"
]
build-backend = "setuptools.build_meta"

[project]
name = "home-lab"
version = "0.0.1"
authors = [
  { name="home-lab", email="ndinhnguyen@gmail.com" },
]
description = "repo process"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]


[tool.pytest.ini_options]
addopts =[
  "-v",
  "--cov=libs"
]

[tool.coverage.report]
skip_empty = true

[tool.setuptools]
packages = ["home-lab"]
package-dir = {"home-lab" = "."}
