---
git_repositories:
  - repo: "https://github.com/phobokhonghanh/home-lab.git"
    dest: "/opt/home-lab"
    version: "main"
# Example:
# git_repositories:
#   - repo: "https://github.com/example/repo.git"
#     dest: "/opt/repo"
#     version: "main"
